services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cbctadmin
      POSTGRES_PASSWORD: bfGWUagcc1!223Vb
      POSTGRES_ROOT_PASSWORD: bfGWUagcc1!223Vb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U cbctadmin"]
      interval: 5s
      retries: 3
    networks:
      - cbct-network
networks:
  cbct-network: